// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook/addressbook.proto

package example.protobuf.addressbook;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:addressbook.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .addressbook.Person people = 1;</code>
   */
  java.util.List<example.protobuf.addressbook.Person> 
      getPeopleList();
  /**
   * <code>repeated .addressbook.Person people = 1;</code>
   */
  example.protobuf.addressbook.Person getPeople(int index);
  /**
   * <code>repeated .addressbook.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .addressbook.Person people = 1;</code>
   */
  java.util.List<? extends example.protobuf.addressbook.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .addressbook.Person people = 1;</code>
   */
  example.protobuf.addressbook.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
