// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/searchservice.proto

package example.protobuf.service;

public final class SearchServiceProtos {
  private SearchServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchById_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchById_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033service/searchservice.proto\032\035addressbo" +
      "ok/addressbook.proto\"\030\n\nSearchById\022\n\n\002id" +
      "\030\002 \001(\0052A\n\rSearchService\0220\n\014searchPerson\022" +
      "\013.SearchById\032\023.addressbook.PersonB4\n\030exa" +
      "mple.protobuf.serviceB\023SearchServiceProt" +
      "osP\001\210\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          example.protobuf.addressbook.AddressBookProtos.getDescriptor(),
        });
    internal_static_SearchById_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SearchById_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchById_descriptor,
        new java.lang.String[] { "Id", });
    example.protobuf.addressbook.AddressBookProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
