// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/searchservice.proto

package example.protobuf.service;

public interface SearchByIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchById)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 2;</code>
   * @return The id.
   */
  int getId();
}
